# Enable C++ support
language: cpp
# OS selection
os:
  - linux
  - osx
# Compiler selection
compiler:
  - clang
  - gcc
# Build steps
script:
  - aclocal
  - automake --add-missing
  - autoconf
  - ./configure
  - make
  - ./par2 -h
  - make check
