name: Build dev binary
on:
  workflow_dispatch:

jobs:
  build-dev1-mac-x64:
    name: Build x64 MacOS binary
    runs-on: macos-latest
    steps:
      - uses: ConorMacBride/install-package@v1
        with:
          brew: automake libomp
      - run: |
          echo "LIBRARY_PATH=`brew --prefix`/lib" >> $GITHUB_ENV
          echo "CC=`brew --prefix llvm`/bin/clang" >> $GITHUB_ENV
          echo "CXX=`brew --prefix llvm`/bin/clang++" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - run: aclocal && automake --warnings=all --add-missing && autoconf --warnings=all
      - run: ./configure --enable-openmp
      - uses: actions/upload-artifact@v3
        with:
          path: ./config.log
          name: configure-macos-x64.log
          retention-days: 5
        if: ${{ failure() }}
      - run: make
      - run: ./par2 -h
      - run: make check
      - run: xz -9e --x86 --lzma2 par2 -c > par2.xz
      - uses: actions/upload-artifact@v3
        with:
          path: ./par2.xz
          name: par2cmdline-turbo-dev-macos-x64.xz
          retention-days: 5

  build-dev1-mac-arm64:
    name: Build arm64 MacOS binary
    # avoid OpenSSL 3.0.2 on 22.04: https://github.com/tpoechtrager/osxcross/issues/349
    runs-on: ubuntu-20.04
    steps:
      - uses: mbround18/setup-osxcross@main  # OSXCROSS_TARGET unavailable in v1.1
        with:
          osx-version: "12.3"
      - run: osxcross-macports install -arm64 libomp
        env:
          MACOSX_DEPLOYMENT_TARGET: "12.3"
          UNATTENDED: 1
      - run: |
          if [ ! -d "$OSXCROSS_TARGET/macports/pkgs/opt/local" ]; then
            echo "Error! Failed to find ${OSXCROSS_TARGET}/macports/pkgs/opt/local folder!"
            exit 1
          fi
          echo "LIBRARY_PATH=$OSXCROSS_TARGET/macports/pkgs/opt/local/lib/libomp" >> $GITHUB_ENV
          echo "CPATH=$OSXCROSS_TARGET/macports/pkgs/opt/local/include/libomp" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - run: aclocal && automake --warnings=all --add-missing && autoconf --warnings=all
      - run: ./configure --enable-openmp --host=aarch64-macos
        env:
          CC: oa64-clang
          CXX: oa64-clang++
          AR: arm64-apple-darwin21.4-ar
          RANLIB: arm64-apple-darwin21.4-ranlib
      - uses: actions/upload-artifact@v3
        with:
          path: ./config.log
          name: configure-macos-arm64.log
          retention-days: 5
        if: ${{ failure() }}
      - run: make
      - run: xz -9e --lzma2 par2 -c > par2.xz
      - uses: actions/upload-artifact@v3
        with:
          path: ./par2.xz
          name: par2cmdline-turbo-dev-macos-arm64.xz
          retention-days: 5
