name: Build release binary
on:
  release:
    types: [published]
  #push:
  #  tags:
  #  - v*.*.*

jobs:
  build-win:
    strategy:
      matrix:
        include:
        - platform: x64
          bcj: -mf=BCJ2
          name: x64
        - platform: Win32
          bcj: -mf=BCJ2
          name: x86
        - platform: ARM64
          bcj: # -mf=ARM64
          name: arm64
    name: Build ${{ matrix.name }} Windows binary
    runs-on: windows-2019
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: actions/checkout@v3
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: msbuild -property:PlatformToolset=ClangCL -property:Configuration=Release -property:Platform={{ matrix.platform }} par2cmdline.sln
      - run: move {{ matrix.platform }}\Release\par2.exe par2.exe && 7z a -t7z -mx=9 {{ matrix.bcj }} par2.7z par2.exe
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }} 
          asset_path: ./par2.7z
          asset_name: par2cmdline-turbo-${{ steps.get_release.outputs.tag_name }}-win-{{ matrix.name }}.7z
          asset_content_type: application/octet-stream
  
  build-linux-static:
    strategy:
      matrix:
        include:
        - target: x86_64-linux-musl
          xz_bcj: --x86
          name: amd64
        - target: aarch64-linux-musl
          xz_bcj: # --arm64 # requires xz utils >=5.4 to decompress
          name: aarch64
        - target: armv7l-linux-musleabihf
          xz_bcj: --arm
          name: armv7l
    name: Build ${{ matrix.name }} Linux static binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Lesmiscore/musl-cross-compilers@heracles
        id: musl
        with:
          target: ${{ matrix.target }}
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: aclocal && automake --warnings=all --add-missing && autoconf --warnings=all
      - run: ./configure
        env:
          CC: ${{ steps.musl.outputs.path }}/${{ matrix.target }}-cc
          CXX: ${{ steps.musl.outputs.path }}/${{ matrix.target }}-c++
          LDFLAGS: -static
      - run: make
      - run: ./par2 -h
        if: ${{ matrix.name }} == 'amd64'
      - run: make check
        if: ${{ matrix.name }} == 'amd64'
      - run: xz -9e ${{ matrix.xz_bcj }} --lzma2 par2 -c > par2.xz
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }} 
          asset_path: ./par2.xz
          asset_name: par2cmdline-turbo-${{ steps.get_release.outputs.tag_name }}-linux-${{ matrix.name }}.xz
          asset_content_type: application/octet-stream

  build-mac-x64:
    name: Build x64 MacOS binary
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: aclocal && automake --warnings=all --add-missing && autoconf --warnings=all
      - run: ./configure
        env:
          LDFLAGS: -static
      - run: make
      - run: ./par2 -h
      - run: make check
      - run: xz -9e --x86 --lzma2 par2 -c > par2.xz
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }} 
          asset_path: ./par2.xz
          asset_name: par2cmdline-turbo-${{ steps.get_release.outputs.tag_name }}-macos-x64.xz
          asset_content_type: application/octet-stream

  build-mac-arm64:
    name: Build arm64 MacOS binary
    runs-on: ubuntu-latest
    steps:
      - uses: mbround18/setup-osxcross@v1
        with:
          osx-version: "12.3"
      - uses: actions/checkout@v3
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: aclocal && automake --warnings=all --add-missing && autoconf --warnings=all
      - run: ./configure
        env:
          CC: oa64e-clang
          CXX: oa64e-clang++
          LDFLAGS: -static
      - run: make
      - run: xz -9e --lzma2 par2 -c > par2.xz
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }} 
          asset_path: ./par2.xz
          asset_name: par2cmdline-turbo-${{ steps.get_release.outputs.tag_name }}-macos-arm64e.xz
          asset_content_type: application/octet-stream
